version: '3.7'

services:
  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    networks:
      - cluster-network

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    depends_on:
      - mongo
    networks:
      - cluster-network

  backend:
    image: code7backend:latest
    container_name: code7backend
    build:
      context: ./Backend
      dockerfile: Api/Dockerfile
    ports:
      - "8082:80"
    environment:
    #it's will replace appsettings configs
      MongoSettings__Host: mongo
      MongoSettings__Port: 27017
    networks:
      - cluster-network
    depends_on:
      - mongo

  frontend:
      image: code7frontend:latest
      container_name: code7frontend
      build: ./Frontend
      ports: 
        - '8083:80'
      networks:
        - cluster-network
      depends_on:
        - backend

networks:
  cluster-network:
    driver: bridge